AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DomainName:
    Type: String
    Default: example.net
  TTL:
    Type: Number
    Default: 600
  MxRecords:
    Type: CommaDelimitedList
    Description: >-
      A comma-separated list of entries for MX servers. Each entry
      should have a priority and domain name, separated by a space.
    Default: 10 spool.mail.gandi.net,50 fb.mail.gandi.net
  DependentStackName:
    Type: String
    Description: >-
      Name of stack we depend on and will grab exported values from.
      Computed by Sceptre.
Resources:
  Zone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "My hosted zone for ${DomainName}"
  MxRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref Zone
      Type: MX
      TTL: !Ref TTL
      ResourceRecords: !Ref MxRecords
  ApexRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref Zone
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue: !Sub "${DependentStackName}-RedirDomain"
        HostedZoneId: Z2FDTNDATAQYW2
  WwwRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Sub "www.${DomainName}"
      HostedZoneId: !Ref Zone
      Type: CNAME
      TTL: !Ref TTL
      ResourceRecords:
        - Fn::ImportValue: !Sub "${DependentStackName}-SiteDomain"
