AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DomainName:
    Type: String
    Default: example.net
  PrimaryMx:
    Type: String
    Default: spool.mail.gandi.net
  SecondaryMx:
    Type: String
    Default: fb.mail.gandi.net
  TTL:
    Type: Number
    Default: 600
  ApexRecords:
    Type: CommaDelimitedList
    Description: >-
      The default here is for GitHub Pages, cf
      https://help.github.com/articles/setting-up-an-apex-domain/
    Default: 192.30.252.153,192.30.252.154
  WwwRecord:
    Type: String
    Description: Set up www.example.net as CNAME for this address
    Default: stig.github.io
Resources:
  Zone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Join
          - " "
          - ["My hosted zone for", !Ref DomainName]
  MxRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref Zone
      Type: MX
      TTL: !Ref TTL
      ResourceRecords:
        - !Join
          - ""
          - [10, " ", !Ref PrimaryMx, "."]
        - !Join
          - ""
          - [50, " ", !Ref SecondaryMx, "."]
  ApexRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref Zone
      Type: A
      TTL: !Ref TTL
      ResourceRecords: !Ref ApexRecords
  WwwRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: !Join
        - ""
        - ['www.', !Ref DomainName, '.']
      HostedZoneId: !Ref Zone
      Type: CNAME
      TTL: !Ref TTL
      ResourceRecords:
        - !Ref WwwRecord
