Parameters:
    DomainName:
        Type: String
        Default: www.superloopy.io
Outputs:
    Hostname:
        Description: "TODO"
        Value: !GetAtt CloudFront.DomainName
    Bucketname:
        Value: !Ref SiteBucket
    LogBucketName:
        Value: !Ref LogBucket
Resources:
    SiteBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            LoggingConfiguration:
                DestinationBucketName: !Ref LogBucket
            WebsiteConfiguration:
                IndexDocument: index.html
    LogBucket:
        Type: "AWS::S3::Bucket"
        Properties:
            AccessControl: LogDeliveryWrite
    CloudFront:
        Type: "AWS::CloudFront::Distribution"
        Properties:
            DistributionConfig:
                Origins:
                    -
                        DomainName:
                            "Fn::Join":
                                - "."
                                -
                                    - !Ref SiteBucket
                                    - "s3-website.eu-west-2.amazonaws.com"
                        Id: origin
                        CustomOriginConfig:
                            OriginProtocolPolicy: http-only
                DefaultCacheBehavior:
                    TargetOriginId: origin
                    DefaultTTL: 5
                    MaxTTL: 30
                    ForwardedValues:
                        QueryString: false
                    ViewerProtocolPolicy: redirect-to-https
                Enabled: true
                Aliases:
                    - !Ref DomainName
                ViewerCertificate:
                    AcmCertificateArn: !Ref SSL
                    SslSupportMethod: sni-only
    SSL:
        Type: "AWS::CertificateManager::Certificate"
        Properties:
            DomainName: !Ref DomainName
