template_path: templates/dns.yaml
parameters:
  DomainName: superloopy.io
  ApexCloudFrontDomain: !stack_output www::ApexCloudFrontDomain
  SiteCloudFrontDomain: !stack_output www::SiteCloudFrontDomain
